### ISSUE TITLE
context.get('currentUser'); is not accessible from User.observe hook

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-context#23]
@barocsi commented on [Fri Jan 29 2016](https://github.com/strongloop/loopback/issues/2004)

I was trying to implement an access filter for my User method depending on the currently logged in user.
However, when I try to access, it is undefined:

``` javascript
User.observe('access', function inspectRoles(ctx, next) {
    var loopback = require('loopback');
    var context = loopback.getCurrentContext();
    var user = context.get('currentUser');
}
```

It works with other presistedModels operation hooks.

---

@jannyHou commented on [Mon Feb 01 2016](https://github.com/strongloop/loopback/issues/2004#issuecomment-178153262)

Hi @barocsi  thanks for your contribution! And any question or suggestion are welcomed! 
I am trying to reproduce the issue with access hook, are you adding it to your custom user model or the build-in User model in loopback?

Could you fork this [sandbox](https://github.com/strongloop/loopback-sandbox) and replace it with your code to prove the problem? Thanks!

---

@barocsi commented on [Mon Feb 01 2016](https://github.com/strongloop/loopback/issues/2004#issuecomment-178161798)

This is a custom user model. I will check against the sandbox repo.

---

@KaanErkol commented on [Thu Mar 31 2016](https://github.com/strongloop/loopback/issues/2004#issuecomment-203788379)

any solutions ?

---

@bajtos commented on [Tue Jun 07 2016](https://github.com/strongloop/loopback/issues/2004#issuecomment-224313210)

Possibly related: https://github.com/strongloop/loopback/issues/2397

---

@jannyHou commented on [Tue Jun 07 2016](https://github.com/strongloop/loopback/issues/2004#issuecomment-224321063)

i am able to reproduce it with the snippet above:

```
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer
user: undefined
```

**Comment by dehypnosis** [comment]
@bajtos any progress?

I don't know the details of CLS thing.
But if you are busy to resolve this, you can give me a hint, so i can contribute..

**Comment by bajtos** [comment]
@dehypnosis I think this may be a general problem of the [CLS](https://www.npmjs.com/package/continuation-local-storage) module we use in `loopback-context@1.x`, most likely it's the `async` library that's breaking the CLS.

Could you please try the latest version of this module and check if the problem is still present? See [Usage](https://github.com/strongloop/loopback-context#usage) for instructions how to setup your app.

**Comment by bajtos** [comment]
> Could you please try the new 2.x version of this module and check if the problem is still present?

Err, I meant the latest version of loopback-context, which is 3.0.0.

**Comment by b-admike** [comment]
@dehypnosis @bajtos I was able to get the current user by following the details in [Usage](https://github.com/strongloop/loopback-context#usage) as pointed out by Miroslav while trying to reproduce [juggler#1250](https://github.com/strongloop/loopback-datasource-juggler/issues/1250) . If you need any help, please let me know.
