### ISSUE TITLE
Add support for node 7

### ISSUE THREAD

**Issue by xnf** [strongloop/loopback-context#29]
### Bug or feature request
- [ ] Bug
- [x] Feature request

### Description of feature (or steps to reproduce if bug)
Cannot install loopback-context with yarn as it complains about "incompatible" node engine: 
> `error loopback-context@3.1.0: The engine "node" is incompatible with this module. Expected version "^4.5 || ^5.10 || ^6.0".`

### Expected result
loopback-context to be compatible with NodeJS v7 or at least package.json to be updated

### Additional information (Node.js version, LoopBack version, etc)
Node v.7.7.1

**Comment by bajtos** [comment]
Released in `loopback-context@3.2.0`.
