### ISSUE TITLE
Can't get context in operation hook, set in Remote Method

### ISSUE THREAD

**Issue by lazzyms** [strongloop/loopback-context#48]
I have done this in remote method :
```
var context = LoopBackContext.getCurrentContext()
context.set('sess', { 'foo': 'bar' })
```
Now, I want to get this in a operation hook, like this :
```
var context = LoopBackContext.getCurrentContext();
context.get('sess')
```

But it get `undefined`.
PS: remote-method and operation hook is in same model
@bajtos @raymondfeng

**Comment by bajtos** [comment]
To be honest, I have no idea what's the status of support for continuation-local-storage (CLS) in Node.js core these days. Depending on the version of Node.js, you may need workaround to make CLS work properly.  Did you follow the instructions in https://github.com/strongloop/loopback-context#setup-cls-hooked?

Personally, I don't recommend using `loopback-context` and advise users to leverage `options` argument instead. See https://loopback.io/doc/en/lb3/Using-current-context.html

**Comment by lazzyms** [comment]
Using express-session with `options` argument when required.
